<?php
/**
 * POST api/patients/create.php
 * Registers a new patient profile linked to a clinic.
 */
require_once __DIR__ . '/../../includes/Auth.php';

$db   = new Database();
$auth = new Auth($db);

// Force active session verification
$auth->requireAuth();

// Authorization Guard (Staff role permitted)
if (!$auth->hasRole('staff') && !$auth->hasRole('admin') && !$auth->hasRole('doctor')) {
    Api::error('You are not authorized for this operation', 403);
    exit;
}

// Ensure proper Request Method
if (Api::method() !== 'POST') { 
    Api::error('Method not allowed.', 405); 
    exit; 
}

// Get the current logged-in user's ID from session for tracking
$currentUserId = $_SESSION['user_id'] ?? null;

if (!$currentUserId) {
    Api::error('User tracking session context not found.', 401);
    exit;
}

// Determine office_id: check POST first, fallback to SESSION if absent or 0
$officeId = (int)($_POST['office_id'] ?? 0);
if ($officeId <= 0) {
    $officeId = (int)($_SESSION['office_id'] ?? 0);
}

// 1. Capture, trim, and sanitize inbound client payload data
$data = [
    'name'        => trim($_POST['name'] ?? ''),
    'dob'         => trim($_POST['dob'] ?? ''),
    'mobile'      => trim($_POST['phone'] ?? ''), // Maps frontend 'phone' to backend DB column 'mobile'
    'email'       => trim($_POST['email'] ?? ''),
    'address'     => trim($_POST['address'] ?? ''),
    'office_id'   => $officeId,
    'created_by'  => (int)$currentUserId,
    'edited_by'   => null, // Expressly set to null on creation as it hasn't been modified yet
    'edited_time' => date('Y-m-d H:i:s') // Set current time stamp for creation defaults
];

// 2. Strict validation check
if (
    empty($data['name']) || 
    empty($data['dob']) || 
    empty($data['mobile']) || 
    empty($data['address']) || 
    $data['office_id'] <= 0
) {
    Api::error('All fields are required, including a valid office assignment context.');
    exit;
}

try {
    // 3. Insert record into the database 'patient' table
    // (id will be automatically generated by AUTO_INCREMENT)
    $patientId = $db->insert('patient', $data);

    if ($patientId) {
        Api::success(['patient_id' => $patientId], 'Patient profile created successfully.');
    } else {
        Api::error('Failed to write patient profile record to database.');
    }

} catch (Exception $e) {
    Api::error('System Database Error: ' . $e->getMessage());
}